---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}

setwd("C:/Documents/Misc/Advent of Code/Advent of Code 2023")
source("Setup.R")
input <- get_input(17L, practice=FALSE)

```

```{r part 1}

tibble(input=input) %>%
  turn_into_matrix() %>%
  runfunc(function(m) {
    mode(m) <- "integer"
    m
  }) %>%  # As integers not characters
  runfunc(function(m) {
    get_nodes <- function(mat) {
      bind_rows(tibble(node="start", r=1L, c=1L, from_dir="NA"), {
        crossing(r=1:nrow(mat), c=1:ncol(mat)) %>%
          crossing(from_dir=c("h", "v")) %>%
          mutate(node=str_c(r, "-", c, "-", from_dir)) %>%
          filter(node %nin% c("1-1-h", "1-1-v"))
      })
    }
    allowed_indices <- function(x, moving_index) {
      which(
        x >= 1L &
          x <= nrow(m) &
          x != moving_index
      )
    }
    
    get_nodes(m) %>%
      mutate(connections=pmap(list(r, c, from_dir), function(r, c, from_dir) {
        moving_index <- if (from_dir %in% c("h", "NA")) r else c
        other_indices <- (moving_index - 3L):(moving_index + 3L) %>%
          { .[allowed_indices(., moving_index)] }
        
        connected_nodes <- character(0)
        if (from_dir %in% c("h", "NA")) connected_nodes <- c(connected_nodes, str_c(other_indices, "-", c, "-v"))
        if (from_dir %in% c("v", "NA")) connected_nodes <- c(connected_nodes, str_c(r, "-", other_indices, "-h"))
        
        weights <- integer(length(other_indices))
        if (from_dir == "h") {
          for (i in 1:length(other_indices)) {
            weights[i] <- sum(m[r:other_indices[i], c]) - m[r,c]
          }
        }
        else if (from_dir == "v") {
          for (i in 1:length(other_indices)) {
            weights[i] <- sum(m[r, c:other_indices[i]]) - m[r,c]
          }
        }
        else {
          for (i in 1:3) {
            weights[i] <- sum(m[r:other_indices[i], c]) - m[r,c]
          }
          for (i in 1:3) {
            weights[i + 3L] <- sum(m[r, c:other_indices[i]]) - m[r,c]
          }
        }
        
        tibble(connection=connected_nodes, weight=weights)
      })) %>%
      unnest(connections) %>%
      mutate(connection=if_else(connection %in% c("1-1-h", "1-1-v"), "start", connection)) %>%
      select(node, connection, weight)
  }) %>%  # Get graph
  runfunc(function(d) {
    get_distance_table <- function(graph, start) {
      graph %>%
        select(node, connection) %>%
        pivot_longer(everything(), values_to="node") %>%
        distinct(node) %>%
        mutate(
          distance=if_else(node == start, 0, Inf),
          must_visit=TRUE
        )
    }
    get_can_reach <- function(graph, at) {
      graph %>%
        filter(node == at) %>%
        select(node="connection", weight)
    }
    get_new_at <- function(distance_table) {
      distance_table %>%
        filter(must_visit) %>%
        filter(distance == min(distance)) %>%
        filter(row_number() == 1L) %>%
        select(node, travelled="distance")
    }
    update_distance_table <- function(distance_table, can_reach, at) {
      distance_table %>%
        left_join(can_reach, join_by(node)) %>%
        mutate(
          must_visit=if_else(node == at$node, FALSE, must_visit),
          new_dist=weight + at$travelled,
          distance=if_else(is.na(weight) | new_dist >= distance, distance, new_dist)
        ) %>%
        select(node, distance, must_visit)
    }
    dijkstra <- function(graph, start) {
      distance_table <- get_distance_table(graph, start)
      
      remaining_visits <- sum(distance_table$must_visit)
      while (remaining_visits > 0L) {
        at <- get_new_at(distance_table)
        can_reach <- get_can_reach(graph, at$node)
        distance_table <- update_distance_table(distance_table, can_reach, at)
        remaining_visits <- sum(distance_table$must_visit)
      }
      distance_table
    }
    
    dijkstra(d, "start")
  }) %>%
  filter(str_detect(node, str_c(length(input), "-", length(input), "-(h|v)"))) %>%
  filter(distance == min(distance)) %>%
  pullfirst(distance)

```

```{r part 2}

tibble(input=input) %>%
  turn_into_matrix() %>%
  runfunc(function(m) {
    mode(m) <- "integer"
    m
  }) %>%  # As integers not characters
  runfunc(function(m) {
    get_nodes <- function(mat) {
      bind_rows(tibble(node="start", r=1L, c=1L, from_dir="NA"), {
        crossing(r=1:nrow(mat), c=1:ncol(mat)) %>%
          crossing(from_dir=c("h", "v")) %>%
          mutate(node=str_c(r, "-", c, "-", from_dir)) %>%
          filter(node %nin% c("1-1-h", "1-1-v"))
      })
    }
    allowed_indices <- function(moving_index) {
      x <- (moving_index - 10L):(moving_index + 10L)
      indices <- which(
        x >= 1 &
          x <= nrow(m) &
          abs(x - moving_index) >= 4L
      )
      x[indices]
    }
    
    get_nodes(m) %>%
      mutate(connections=pmap(list(r, c, from_dir), function(r, c, from_dir) {
        moving_index <- if (from_dir %in% c("h", "NA")) r else c
        other_indices <- allowed_indices(moving_index)
        
        connected_nodes <- character(0)
        if (from_dir %in% c("h", "NA")) connected_nodes <- c(connected_nodes, str_c(other_indices, "-", c, "-v"))
        if (from_dir %in% c("v", "NA")) connected_nodes <- c(connected_nodes, str_c(r, "-", other_indices, "-h"))
        
        weights <- integer(length(other_indices))
        if (from_dir == "h") {
          for (i in 1:length(other_indices)) {
            weights[i] <- sum(m[r:other_indices[i], c]) - m[r,c]
          }
        }
        else if (from_dir == "v") {
          for (i in 1:length(other_indices)) {
            weights[i] <- sum(m[r, c:other_indices[i]]) - m[r,c]
          }
        }
        else {
          for (i in 1:7) {
            weights[i] <- sum(m[r:other_indices[i], c]) - m[r,c]
          }
          for (i in 1:7) {
            weights[i + 7L] <- sum(m[r, c:other_indices[i]]) - m[r,c]
          }
        }
        
        tibble(connection=connected_nodes, weight=weights)
      })) %>%
      unnest(connections) %>%
      mutate(connection=if_else(connection %in% c("1-1-h", "1-1-v"), "start", connection)) %>%
      select(node, connection, weight)
  }) %>%  # Get graph
  runfunc(function(d) {
    get_distance_table <- function(graph, start) {
      graph %>%
        select(node, connection) %>%
        pivot_longer(everything(), values_to="node") %>%
        distinct(node) %>%
        mutate(
          distance=if_else(node == start, 0, Inf),
          must_visit=TRUE
        )
    }
    get_can_reach <- function(graph, at) {
      graph %>%
        filter(node == at) %>%
        select(node="connection", weight)
    }
    get_new_at <- function(distance_table) {
      distance_table %>%
        filter(must_visit) %>%
        filter(distance == min(distance)) %>%
        filter(row_number() == 1L) %>%
        select(node, travelled="distance")
    }
    update_distance_table <- function(distance_table, can_reach, at) {
      distance_table %>%
        left_join(can_reach, join_by(node)) %>%
        mutate(
          must_visit=if_else(node == at$node, FALSE, must_visit),
          new_dist=weight + at$travelled,
          distance=if_else(is.na(weight) | new_dist >= distance, distance, new_dist)
        ) %>%
        select(node, distance, must_visit)
    }
    dijkstra <- function(graph, start) {
      distance_table <- get_distance_table(graph, start)
      
      remaining_visits <- sum(distance_table$must_visit)
      while (remaining_visits > 0L) {
        at <- get_new_at(distance_table)
        can_reach <- get_can_reach(graph, at$node)
        distance_table <- update_distance_table(distance_table, can_reach, at)
        remaining_visits <- sum(distance_table$must_visit)
      }
      distance_table
    }
    
    dijkstra(d, "start")
  }) %>%
  filter(str_detect(node, str_c(length(input), "-", length(input), "-(h|v)"))) %>%
  filter(distance == min(distance)) %>%
  pullfirst(distance)

```
