---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}

setwd("C:/Documents/Misc/Advent of Code/Advent of Code 2023")
source("Setup.R")
input <- get_input(18L, practice=FALSE)

```

```{r part 1}

tibble(input=input) %>%
  mutate(input=str_split(input, " ")) %>%
  transmute(
    dir=map_chr(input, ~ .x[1]),
    len=map_chr(input, ~ .x[2]),
    colour=map_chr(input, ~ .x[3]) %>% str_remove_all("\\(|\\)")
  ) %>%
  runfunc(function(d) {
    get_dir_to_coord_sum <- function(dir) {
      if (dir == "U") c(-1L, 0L)
      else if (dir == "R") c(0L, 1L)
      else if (dir == "D") c(1L, 0L)
      else if (dir == "L") c(0L, -1L)
    }
    size <- 1000L
    coord <- (size %/% 2L) %>% { c(., .) }
    mat <- matrix(" ", nrow=size, ncol=size)
    
    for (i in 1:nrow(d)) {
      coord_sum <- get_dir_to_coord_sum(d[i,]$dir)
      len <- d[i,]$len
      for (j in 1:len) {
        coord <- coord + coord_sum
        mat[coord[1], coord[2]] <- "#"
      }
    }
    
    mat %>%
      runfunc(function(m) {
        row_bounds <- {
          map_chr(1:nrow(mat), ~ mat[.x,] %>% str_c(collapse="")) %>%
            tibble(r=.) %>%
            mutate(
              id=1:n(),
              test=str_detect(r, "#")
            ) %>%
            filter(test) %>%
            summarise(
              max=max(id),
              min=min(id)
            )
        }
        col_bounds <- {
          map_chr(1:nrow(mat), ~ mat[,.x] %>% str_c(collapse="")) %>%
            tibble(c=.) %>%
            mutate(
              id=1:n(),
              test=str_detect(c, "#")
            ) %>%
            filter(test) %>%
            summarise(
              max=max(id),
              min=min(id)
            )
        }
        
        m[row_bounds$min:row_bounds$max, col_bounds$min:col_bounds$max]
      })
  }) %>%
  runfunc(function(m) {
    get_children_coords <- function(coord) {
      list(
        coord + c(-1L, 0L),
        coord + c(0L, 1L),
        coord + c(1L, 0L),
        coord + c(0L, -1L)
      )
    }
    
    work_mat <- m
    start <- c(ceiling(nrow(m) / 2), ceiling(ncol(m) / 2))
    work_mat[start[1], start[2]] <- "#"
    work_tib <- tibble(row=start[1], col=start[2])
    
    while(nrow(work_tib) > 0L) {
      work_tib <- work_tib %>%
        mutate(children={
          map2(row, col, ~ get_children_coords(c(.x, .y))) %>%
            map(function(l) {
              keep(l, function(coord) {
                outcome <- work_mat[coord[1], coord[2]] == " "
                if (outcome) work_mat[coord[1], coord[2]] <<- "#"
                outcome
              })
            })
        }) %>%
        unnest(children) %>%
        mutate(
          row=map_int(children, ~ .x[1]),
          col=map_int(children, ~ .x[2])
        )
    }
    
    sum(work_mat == "#")
  })

  runfunc(function(m) {
    map(1:nrow(m), ~ m[.x,]) %>%
      map2(1:length(.), ~ tibble(row=.y, col=1:length(.x), x=.x)) %>%
      reduce(bind_rows) %>%
      ggplot(aes(col, row, fill=x)) +
        geom_tile(show.legend=FALSE) +
        scale_y_reverse(breaks=NULL) +
        scale_x_continuous(breaks=NULL) +
        labs(x=NULL, y=NULL) +
        theme(axis.line=element_blank()) +
        coord_fixed()
  })  # Visualise

```

```{r part 2}

tibble(input=input) %>%
  mutate(input=str_split(input, " ")) %>%
  transmute(
    colour=map_chr(input, ~ .x[3]) %>% str_remove_all("\\(|\\)|#") %>% str_split(""),
    row=1:n(),
    col=map(colour, ~ 1:length(.x))
  ) %>%
  unnest(c(col, colour)) %>%
  pivot_wider(names_from=col, values_from=colour) %>%
  mutate(
    dir=recode(`6`, "0"="R", "1"="D", "2"="L", "3"="U"),
    across(c(`1`:`5`), function(x) {
      recode(x, "a"="10", "b"="11", "c"="12", "d"="13", "e"="14", "f"="15") %>%
        as.integer()
    }),
    `4`=`4` * 16L,
    `3`=`3` * as.integer(16L^2L),
    `2`=`2` * as.integer(16L^3L),
    `1`=`1` * as.integer(16L^4L),
    total=`1` + `2` + `3` + `4` + `5`
  ) %>%
  select(dir, total) %>%
  runfunc(function(d) {
    # Functions ----
    get_dir_to_coord_sum <- function(dir) {
      if (dir == "U") c(-1L, 0L)
      else if (dir == "R") c(0L, 1L)
      else if (dir == "D") c(1L, 0L)
      else if (dir == "L") c(0L, -1L)
    }
    
    # Set up objects ----
    coordinates <- {
      d %>%
        mutate(
          coord_sum=map(dir, get_dir_to_coord_sum),
          r_change=map_int(coord_sum, ~ .x[1]) * total,
          c_change=map_int(coord_sum, ~ .x[2]) * total,
          row=cumsum(r_change),
          col=cumsum(c_change)
        ) %>%
        select(row, col)
    }
    intersections <- {
      distinct(coordinates, row) %>%
        crossing(distinct(coordinates, col))
    }
    rectangles <- {
      intersections %>%
        rename(tl_row="row", tl_col="col") %>%
        inner_join({
          (.) %>%
            rename(tr_row="tl_row", tr_col="tl_col")
        }, join_by(tl_row == tr_row, closest(tl_col < tr_col))) %>%
        inner_join({
          (.) %>%
            select(tl_row, tl_col) %>%
            rename(bl_row="tl_row", bl_col="tl_col")
        }, join_by(tl_col == bl_col, closest(tl_row < bl_row))) %>%
        mutate(
          width=tr_col - tl_col,
          height=bl_row - tl_row,
          area=as.numeric(width) * as.numeric(height),
          id=1:n()
        ) %>%
        select(
          id,
          tl_row, tl_col,
          tr_col, bl_row,
          width, height,
          area
        )
    }
    neighbours <- {
      runfunc(function() {
        r <- {
          rectangles %>%
            select(id, tl_row, tr_col) %>%
            inner_join({
              rectangles %>%
                select(right="id", tl_row, tl_col)
            }, join_by(tl_row, tr_col == tl_col)) %>%
            select(id, right)
        }
        b <- {
          rectangles %>%
            select(id, bl_row, tl_col) %>%
            inner_join({
              rectangles %>%
                select(below="id", tl_row, tl_col)
            }, join_by(tl_col, bl_row == tl_row)) %>%
            select(id, below)
        }
        l <- {
          rectangles %>%
            select(id, tl_col, tl_row) %>%
            inner_join({
              rectangles %>%
                select(left="id", tr_col, tl_row)
            }, join_by(tl_row, tl_col == tr_col)) %>%
            select(id, left)
        }
        a <- {
          rectangles %>%
            select(id, tl_row, tl_col) %>%
            inner_join({
              rectangles %>%
                select(above="id", bl_row, tl_col)
            }, join_by(tl_col, tl_row == bl_row)) %>%
            select(id, above)
        }
        tr <- {
          rectangles %>%
            select(id, tl_row, tr_col) %>%
            inner_join({
              rectangles %>%
                select(top_right="id", bl_row, tl_col)
            }, join_by(tl_row == bl_row, tr_col == tl_col)) %>%
            select(id, top_right)
        }
        
        rectangles %>%
          select(id) %>%
          left_join(r, join_by(id)) %>%
          left_join(b, join_by(id)) %>%
          left_join(l, join_by(id)) %>%
          left_join(a, join_by(id)) %>%
          left_join(tr, join_by(id)) %>%
          pivot_longer(-id, names_to="type", values_to="neighbour_id") %>%
          filter(!is.na(neighbour_id))
      })
    }
    lines <- {
      coordinates %>%
        mutate(across(c(row, col), ~ c(.x[n()], .x[1:(n() - 1L)]))) %>%
        rename(row_start="row", col_start="col") %>%
        mutate(
          row_end=c(row_start[2:n()], row_start[1]),
          col_end=c(col_start[2:n()], col_start[1]),
          type=if_else(row_start == row_end, "horizontal", "vertical"),
          col_min=pmin(col_start, col_end),
          col_max=pmax(col_start, col_end),
          row_min=pmin(row_start, row_end),
          row_max=pmax(row_start, row_end),
          col_start=col_min,
          col_end=col_max,
          row_start=row_min,
          row_end=row_max
        ) %>%
        select(type, row_start, row_end, col_start, col_end)
    }
    segments <- runfunc(function() {
      hor_segments <- {
        lines %>%
          filter(type == "horizontal") %>%
          runfunc(function(x) {
            x %>%
              inner_join(
                intersections,
                join_by(
                  row_start == row,
                  col_start <= col,
                  col_end >= col
                )
              ) %>%
              mutate(row=row_start) %>%
              nest_by(type, row_start, row_end, col_start, col_end)
          }) %>%
          mutate(data=map(data, function(x) {
            x %>%
              arrange(col) %>%
              mutate(
                type="horizontal",
                row_start=row,
                row_end=row,
                col_start=col,
                col_end=c(col[2:n()], NA_integer_)
              ) %>%
              filter(!is.na(col_end)) %>%
              select(type, row_start, row_end, col_start, col_end)
          })) %>%
          select(data) %>%
          unnest(data)
      }
      vert_segments <- {
        lines %>%
          filter(type == "vertical") %>%
          runfunc(function(x) {
            x %>%
              inner_join(
                intersections,
                join_by(
                  col_start == col,
                  row_start <= row,
                  row_end >= row
                )
              ) %>%
              mutate(col=col_start) %>%
              nest_by(type, row_start, row_end, col_start, col_end)
          }) %>%
          mutate(data=map(data, function(x) {
            x %>%
              arrange(row) %>%
              mutate(
                type="vertical",
                col_start=col,
                col_end=col,
                row_start=row,
                row_end=c(row[2:n()], NA_integer_)
              ) %>%
              filter(!is.na(row_end)) %>%
              select(type, row_start, row_end, col_start, col_end)
          })) %>%
          select(data) %>%
          unnest(data)
      }
      
      bind_rows(hor_segments, vert_segments)
    })
    start_rect_id <- {
      rectangles %>%
        crossing({
          coordinates %>%
            summarise(
              max_r=max(row),
              min_r=min(row),
              max_c=max(col),
              min_c=min(col)
            ) %>%
            transmute(
              mid_row=(min_r + ((max_r - min_r) / 2)) %>% ceiling() %>% as.integer(),
              mid_col=(min_c + ((max_c - min_c) / 2)) %>% ceiling() %>% as.integer()
            )
        }) %>%
        mutate(
          diff_r=abs(tl_row - mid_row),
          diff_c=abs(tl_col - mid_col)
        ) %>%
        filter(
          diff_r == min(diff_r),
          diff_c == min(diff_c)
        ) %>%
        pull(id)
    }
    
    # Algorithm ----
    in_recs <- rectangles %>% filter(id == start_rect_id)
    special_case_borders <- tibble()
    i <- 1L
    while(i <= nrow(in_recs)) {
      print(i)
      current_id <- in_recs[i,]$id
      current_neighbours <- neighbours %>% filter(id == current_id, type != "top_right")
      neigbour_segments <- {
        in_recs[i,] %>%
          select(tl_row, tl_col, tr_col, bl_row) %>%
          crossing(type=c("right", "below", "left", "above")) %>%
          arrange(type) %>%
          mutate(
            row_start=c(tl_row[1], bl_row[2], tl_row[3], tl_row[4]),
            row_end=  c(tl_row[1], bl_row[2], bl_row[3], bl_row[4]),
            col_start=c(tl_col[1], tl_col[2], tl_col[3], tr_col[4]),
            col_end=  c(tr_col[1], tr_col[2], tl_col[3], tr_col[4])
          ) %>%
          select(type, row_start, row_end, col_start, col_end) %>%
          semi_join(
            segments,
            join_by(row_start, row_end, col_start, col_end)
          )
      }
      special_case_borders <- bind_rows(special_case_borders, {
        tibble(
          id=current_id,
          has_right="right" %in% neigbour_segments$type,
          has_below="below" %in% neigbour_segments$type,
          has_both=has_right & has_below
        )
      })
      neighbours_added <- {
        current_neighbours %>%
          anti_join(neigbour_segments, join_by(type)) %>%
          anti_join(in_recs, join_by(neighbour_id == id)) %>%
          pull(neighbour_id)
      }
      in_recs <- in_recs %>% bind_rows(rectangles %>% filter(id %in% neighbours_added))
      i <- i + 1L
    }
    concave_lefts <- {
      in_recs %>%
        select(id) %>%
        inner_join(neighbours %>% nest_by(id), join_by(id)) %>%
        mutate(
          data=map(data, ~ .x %>% filter(neighbour_id %in% in_recs$id)),
          above=map_lgl(data, ~ "above" %in% .x$type),
          no_right=map_lgl(data, ~ "right" %nin% .x$type),
          top_right=map_lgl(data, ~ "top_right" %in% .x$type),
          concave_left=above & no_right & top_right
        ) %>%
        summarise(sum(concave_left)) %>%
        deframe()
    }
    
    in_recs %>%
      inner_join(special_case_borders, join_by(id)) %>%
      mutate(tot_area=area + {
        if_else(has_right, as.numeric(height), 0)
      } + {
        if_else(has_below, as.numeric(width), 0)
      } + {
        if_else(has_both, 1, 0)
      }) %>%
      summarise(sum(tot_area)) %>%
      deframe() %>%
      { . - concave_lefts } %>%
      as.character()
  })
    
```

```{r}

coordinates %>%
  ggplot(aes(col, row)) +
    geom_polygon() +
    geom_hline(yintercept=0, colour="red") +
    geom_vline(xintercept=0, colour="red")

in_recs %>%
  ggplot(aes(
    xmin=tl_col, xmax=tr_col,
    ymin=tl_row, ymax=bl_row
  )) +
    geom_rect()

```
