---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}

setwd("C:/Documents/Misc/Advent of Code/Advent of Code 2023")
source("Setup.R")
input <- get_input(22L, practice=FALSE)

```

```{r part 1}

tibble(input=input) %>%
  mutate(
    input=str_split(input, "~"),
    start=map_chr(input, ~ .x[1]),
    end=map_chr(input, ~ .x[2]),
    across(c(start, end), function(x) {
      map(x, function(x) {
          str_split(x, ",") %>%
          unlist() %>%
          as.integer()
      })
    }),
    type=map2_chr(start, end, function(start, end) {
      if (start[1] != end[1]) "across"
      else if (start[2] != end[2]) "in"
      else if (start[3] != end[3]) "up"
      else "across"
    }),
    coords=pmap(list(start, end, type), function(start, end, type) {
      l <- list()
      if (type == "across") {
        dim_cubes <- start[1]:end[1]
        for (i in 1:length(dim_cubes)) {
          l[[i]] <- c(dim_cubes[i], start[2], start[3])
        }
      }
      else if (type == "in") {
        dim_cubes <- start[2]:end[2]
        for (i in 1:length(dim_cubes)) {
          l[[i]] <- c(start[1], dim_cubes[i], start[3])
        }
      }
      else if (type == "up") {
        dim_cubes <- start[3]:end[3]
        for (i in 1:length(dim_cubes)) {
          l[[i]] <- c(start[1], start[2], dim_cubes[i])
        }
      }
      l
    }),
    min_level=map_int(coords, function(coords) {
      map_int(coords, ~ .x[3]) %>%
        min()
    })
  ) %>%
  arrange(min_level) %>%
  mutate(id=1:n()) %>%
  select(id, type, coords) %>%
  runfunc(function(d) {
    get_shift <- function(dim) {
      map_int(d$coords, function(x) {
        map_int(x, ~ .x[dim]) %>%
          min()
      }) %>%
        min() %>%
        { 1L - . }
    }
    x_shift <- get_shift(1)
    y_shift <- get_shift(2)
    
    d %>%
      mutate(coords=map(coords, function(coords) {
        map(coords, function(coord) {
          coord + c(x_shift, y_shift, 0L)
        })
      }))
  }) %>%  # Shift everything so it can be contained in array
  runfunc(function(d) {
    get_max <- function(dim) {
      map_int(d$coords, function(x) {
        map_int(x, ~ .x[dim]) %>%
          max()
      }) %>%
        max()
    }
    
    arr <- array(" ", dim=c(get_max(1), get_max(2), get_max(3)))
    
    for (i in 1:nrow(d)) {
      coords <- d[i,]$coords[[1]]
      for (j in 1:length(coords)) {
        coord <- coords[[j]]
        arr[coord[1], coord[2], coord[3]] <- as.character(i)
      }
    }
    
    arr
  }) %>%  # Get array
  runfunc(function(a) {
    is_vert <- function(coords) {
      {
        coords[,3] %>%
          unique() %>%
          length() %>%
          { . != 1L }
      } || nrow(coords) == 1L
    }
    fall_blocks <- function(arr) {
      for (id in 1:max_id) {
        coords <- which(arr == as.character(id), arr.ind=TRUE)
        if (nrow(coords) == 0L) next
        
        if (is_vert(coords)) {
          bottom <- coords[,3] %>% min()
          if (bottom == 1L) next
          spaces_to_drop <- {
            arr[coords[1,1], coords[1,2], 1:(bottom - 1L)] %>%
              rev() %>%
              { . != " " } %>%
              cumsum() %>%
              { sum(. == 0L) }
          }
          if (spaces_to_drop > 0L) {
            arr[coords[1,1], coords[1,2], coords[,3]] <- " "
            arr[coords[1,1], coords[1,2], coords[,3] - spaces_to_drop] <- as.character(id)
          }
        }
        else {
          if (coords[1,3] == 1L) next
          spaces_to_drop <- {
            arr[unique(coords[,1]), unique(coords[,2]), 1:(coords[1,3] - 1L)] %>%
              { . != " " } %>%
              runfunc(function(x) {
                if (is.array(x)) {
                  colSums(x) %>%
                    rev() %>%
                    cumsum() %>%
                    { sum(. == 0L) }
                }
                else {
                  x
                  if (sum(x) == 0L) 1L
                  else 0L
                }
              })
          }
          if (spaces_to_drop > 0L) {
            arr[unique(coords[,1]), unique(coords[,2]), coords[1,3]] <- " "
            arr[unique(coords[,1]), unique(coords[,2]), coords[1,3] - spaces_to_drop] <- as.character(id)
          }
        }
      }
      
      arr
    }
    blocks_will_fall_check <- function(arr) {
      for (id in 1:max_id) {
        coords <- which(arr == as.character(id), arr.ind=TRUE)
        if (nrow(coords) == 0L) next
        
        if (is_vert(coords)) {
          bottom <- coords[,3] %>% min()
          if (bottom == 1L) next
          spaces_to_drop <- {
            arr[coords[1,1], coords[1,2], 1:(bottom - 1L)] %>%
              rev() %>%
              { . != " " } %>%
              cumsum() %>%
              { sum(. == 0L) }
          }
          if (spaces_to_drop > 0L) return(TRUE)
        }
        else {
          if (coords[1,3] == 1L) next
          spaces_to_drop <- {
            arr[unique(coords[,1]), unique(coords[,2]), 1:(coords[1,3] - 1L)] %>%
              { . != " " } %>%
              runfunc(function(x) {
                if (is.array(x)) {
                  colSums(x) %>%
                    rev() %>%
                    cumsum() %>%
                    { sum(. == 0L) }
                }
                else {
                  x
                  if (sum(x) == 0L) 1L
                  else 0L
                }
              })
          }
          if (spaces_to_drop > 0L) return(TRUE)
        }
      }
      return(FALSE)
    }
    
    max_id <- as.integer(a) %>% max(na.rm=TRUE)
    fallen <- fall_blocks(a)
    
    tibble(id=1:max_id) %>%
      mutate(can_disintegrate=map_lgl(id, function(id) {
        print(id)
        with_deletion <- fallen
        coords <- which(fallen == as.character(id), arr.ind=TRUE)
        with_deletion[unique(coords[,1]), unique(coords[,2]), unique(coords[,3])] <- " "
        !blocks_will_fall_check(with_deletion)
      })) %>%
      summarise(sum(can_disintegrate)) %>%
      deframe()
  })

```

```{r part 2}

tibble(input=input) %>%
  mutate(
    input=str_split(input, "~"),
    start=map_chr(input, ~ .x[1]),
    end=map_chr(input, ~ .x[2]),
    across(c(start, end), function(x) {
      map(x, function(x) {
          str_split(x, ",") %>%
          unlist() %>%
          as.integer()
      })
    }),
    type=map2_chr(start, end, function(start, end) {
      if (start[1] != end[1]) "across"
      else if (start[2] != end[2]) "in"
      else if (start[3] != end[3]) "up"
      else "across"
    }),
    coords=pmap(list(start, end, type), function(start, end, type) {
      l <- list()
      if (type == "across") {
        dim_cubes <- start[1]:end[1]
        for (i in 1:length(dim_cubes)) {
          l[[i]] <- c(dim_cubes[i], start[2], start[3])
        }
      }
      else if (type == "in") {
        dim_cubes <- start[2]:end[2]
        for (i in 1:length(dim_cubes)) {
          l[[i]] <- c(start[1], dim_cubes[i], start[3])
        }
      }
      else if (type == "up") {
        dim_cubes <- start[3]:end[3]
        for (i in 1:length(dim_cubes)) {
          l[[i]] <- c(start[1], start[2], dim_cubes[i])
        }
      }
      l
    }),
    min_level=map_int(coords, function(coords) {
      map_int(coords, ~ .x[3]) %>%
        min()
    })
  ) %>%
  arrange(min_level) %>%
  mutate(id=1:n()) %>%
  select(id, type, coords) %>%
  runfunc(function(d) {
    get_shift <- function(dim) {
      map_int(d$coords, function(x) {
        map_int(x, ~ .x[dim]) %>%
          min()
      }) %>%
        min() %>%
        { 1L - . }
    }
    x_shift <- get_shift(1)
    y_shift <- get_shift(2)
    
    d %>%
      mutate(coords=map(coords, function(coords) {
        map(coords, function(coord) {
          coord + c(x_shift, y_shift, 0L)
        })
      }))
  }) %>%  # Shift everything so it can be contained in array
  runfunc(function(d) {
    get_max <- function(dim) {
      map_int(d$coords, function(x) {
        map_int(x, ~ .x[dim]) %>%
          max()
      }) %>%
        max()
    }
    
    arr <- array(" ", dim=c(get_max(1), get_max(2), get_max(3)))
    
    for (i in 1:nrow(d)) {
      coords <- d[i,]$coords[[1]]
      for (j in 1:length(coords)) {
        coord <- coords[[j]]
        arr[coord[1], coord[2], coord[3]] <- as.character(i)
      }
    }
    
    arr
  }) %>%  # Get array
  runfunc(function(a) {
    is_vert <- function(coords) {
      {
        coords[,3] %>%
          unique() %>%
          length() %>%
          { . != 1L }
      } || nrow(coords) == 1L
    }
    fall_blocks <- function(arr) {
      for (id in 1:max_id) {
        coords <- which(arr == as.character(id), arr.ind=TRUE)
        if (nrow(coords) == 0L) next
        
        if (is_vert(coords)) {
          bottom <- coords[,3] %>% min()
          if (bottom == 1L) next
          spaces_to_drop <- {
            arr[coords[1,1], coords[1,2], 1:(bottom - 1L)] %>%
              rev() %>%
              { . != " " } %>%
              cumsum() %>%
              { sum(. == 0L) }
          }
          if (spaces_to_drop > 0L) {
            arr[coords[1,1], coords[1,2], coords[,3]] <- " "
            arr[coords[1,1], coords[1,2], coords[,3] - spaces_to_drop] <- as.character(id)
          }
        }
        else {
          if (coords[1,3] == 1L) next
          spaces_to_drop <- {
            arr[unique(coords[,1]), unique(coords[,2]), 1:(coords[1,3] - 1L)] %>%
              { . != " " } %>%
              runfunc(function(x) {
                if (is.array(x)) {
                  colSums(x) %>%
                    rev() %>%
                    cumsum() %>%
                    { sum(. == 0L) }
                }
                else {
                  x
                  if (sum(x) == 0L) 1L
                  else 0L
                }
              })
          }
          if (spaces_to_drop > 0L) {
            arr[unique(coords[,1]), unique(coords[,2]), coords[1,3]] <- " "
            arr[unique(coords[,1]), unique(coords[,2]), coords[1,3] - spaces_to_drop] <- as.character(id)
          }
        }
      }
      
      arr
    }
    
    max_id <- as.integer(a) %>% max(na.rm=TRUE)
    fallen <- fall_blocks(a)
    
    tibble(id=1:max_id) %>%
      mutate(blocks_that_fell=map_int(id, function(id) {
        print(id)
        with_deletion <- fallen
        coords <- which(fallen == as.character(id), arr.ind=TRUE)
        with_deletion[unique(coords[,1]), unique(coords[,2]), unique(coords[,3])] <- " "
        new_fallen <- fall_blocks(with_deletion)
        new_fallen[which(with_deletion != new_fallen)] %>%
          { .[which(. != " ")] } %>%
          unique() %>%
          length()
      })) %>%
      summarise(sum(blocks_that_fell)) %>%
      deframe()
  })

```
